---
stages:
  - lint
  - deployment test

before_script:
  - ansible --version
  - molecule --version

Ansible lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - ansible-lint -c .ansible-lint `find . -regex ".*\.\(yml\)"`
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - delegated

EPC Jenkins:
  variables:
    MOLECULE_INCLUDE_ANSIBLE_CFG: "True"
    EPC_REGION: EPAM-HU1
  stage: deployment test
  script:
    - molecule test -s cloud-epc
  tags:
    - delegated

AWS Jenkins:
  variables:
    MOLECULE_INCLUDE_ANSIBLE_CFG: "True"
    EPC_REGION: AWS-EUCENTRAL
  stage: deployment test
  script:
    - molecule test -s cloud-aws
  tags:
    - delegated
