---
- name: Global Tool Configuration - JDK
  jenkins_script:
    url: '{{ jenkins2_config_proto }}://{{ jenkins2_host_address }}:{{ jenkins2_config_http_port }}'
    script: '{{ lookup("template", jenkins2_globaltools_jdk_template + ".j2") }}'
    user: '{{ jenkins2_cli_username }}'
    password: '{{ jenkins2_cli_password }}'
    validate_certs: false
    timeout: 120
