---
- name: Read private key
  slurp:
    src: '{{ jenkins2_home_directory }}/{{ jenkins2_local_pkey_file_name }}'
  register: jenkins2_pr_key

- name: Read public key
  slurp:
    src: '{{ jenkins2_home_directory }}/{{ jenkins2_local_cert_file_name }}'
  register: jenkins2_pub_key

- name: Create keystore
  java_keystore:
    name: '{{ jenkins2_ca_domain }}'
    certificate: '{{ jenkins2_pub_key["content"] | b64decode }}'
    private_key: '{{ jenkins2_pr_key["content"] | b64decode }}'
    password: '{{ jenkins2_ssl_key_store_password }}'
    dest: '{{ jenkins2_ssl_key_store }}'
    owner: '{{ jenkins2_user }}'
    group: '{{ jenkins2_user }}'
    mode: 0644
    force: True
  become_flags: '-i'
  become_method: sudo
